<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\LibraryBook;

class LibraryBookSeeder extends Seeder
{
    public function run()
    {
        $books = [
            // === SCHOOL ID 1 ===
            [
                'school_id' => 1,
                'isbn' => '9789976000001',
                'title' => 'Chemistry for Secondary Schools - Book 1',
                'author' => 'Dr. James Mwakasege',
                'publisher' => 'TIE',
                'edition' => '1st',
                'year_published' => 2019,
                'category' => 'Science',
                'price' => 15000,
                'quantity' => 10,
                'available_quantity' => 8,
                'rack_number' => 'S1-R1',
                'status' => 'available',
            ],
            [
                'school_id' => 1,
                'isbn' => '9789976000002',
                'title' => 'Physics Form Two',
                'author' => 'C. Kileo',
                'publisher' => 'Mkuki na Nyota',
                'edition' => '2nd',
                'year_published' => 2018,
                'category' => 'Science',
                'price' => 14000,
                'quantity' => 15,
                'available_quantity' => 13,
                'rack_number' => 'S1-R2',
                'status' => 'available',
            ],
            [
                'school_id' => 1,
                'isbn' => '9789976000003',
                'title' => 'Basic Mathematics - Form One',
                'author' => 'A. Mwandambo',
                'publisher' => 'Oxford Tanzania',
                'edition' => '3rd',
                'year_published' => 2020,
                'category' => 'Mathematics',
                'price' => 13000,
                'quantity' => 12,
                'available_quantity' => 10,
                'rack_number' => 'M1-R1',
                'status' => 'available',
            ],
            [
                'school_id' => 1,
                'isbn' => '9789976000004',
                'title' => 'Biology Form Three',
                'author' => 'Elizabeth Mbise',
                'publisher' => 'Pearson',
                'edition' => '1st',
                'year_published' => 2021,
                'category' => 'Science',
                'price' => 16000,
                'quantity' => 10,
                'available_quantity' => 7,
                'rack_number' => 'S1-R3',
                'status' => 'available',
            ],
            [
                'school_id' => 1,
                'isbn' => '9789976000005',
                'title' => 'English Grammar and Composition',
                'author' => 'John M. Ngonyani',
                'publisher' => 'Macmillan Tanzania',
                'edition' => '2nd',
                'year_published' => 2017,
                'category' => 'Languages',
                'price' => 11000,
                'quantity' => 14,
                'available_quantity' => 14,
                'rack_number' => 'L1-R1',
                'status' => 'available',
            ],
            [
                'school_id' => 1,
                'isbn' => '9789976000006',
                'title' => 'Kiswahili Sanifu kwa Sekondari',
                'author' => 'Asha Mtemvu',
                'publisher' => 'TIE',
                'edition' => '1st',
                'year_published' => 2016,
                'category' => 'Languages',
                'price' => 12000,
                'quantity' => 13,
                'available_quantity' => 9,
                'rack_number' => 'L1-R2',
                'status' => 'available',
            ],
            [
                'school_id' => 1,
                'isbn' => '9789976000007',
                'title' => 'Geography of East Africa',
                'author' => 'N. Kimambo',
                'publisher' => 'Longhorn',
                'edition' => '3rd',
                'year_published' => 2019,
                'category' => 'Humanities',
                'price' => 14500,
                'quantity' => 11,
                'available_quantity' => 8,
                'rack_number' => 'H1-R1',
                'status' => 'available',
            ],
            [
                'school_id' => 1,
                'isbn' => '9789976000008',
                'title' => 'Civics and Ethics - Form One',
                'author' => 'P. Msongole',
                'publisher' => 'Tanzania Publishing House',
                'edition' => '1st',
                'year_published' => 2018,
                'category' => 'Civics',
                'price' => 10000,
                'quantity' => 15,
                'available_quantity' => 12,
                'rack_number' => 'C1-R1',
                'status' => 'available',
            ],
            [
                'school_id' => 1,
                'isbn' => '9789976000009',
                'title' => 'History of Africa',
                'author' => 'Emmanuel King',
                'publisher' => 'TIE',
                'edition' => '1st',
                'year_published' => 2020,
                'category' => 'History',
                'price' => 13500,
                'quantity' => 10,
                'available_quantity' => 9,
                'rack_number' => 'H1-R2',
                'status' => 'available',
            ],
            [
                'school_id' => 1,
                'isbn' => '9789976000010',
                'title' => 'Bookkeeping Principles',
                'author' => 'E. Chuma',
                'publisher' => 'Eastern Publishers',
                'edition' => '2nd',
                'year_published' => 2015,
                'category' => 'Business',
                'price' => 12500,
                'quantity' => 12,
                'available_quantity' => 10,
                'rack_number' => 'B1-R1',
                'status' => 'available',
            ],

            // === SCHOOL ID 2 === (similar pattern)
            [
                'school_id' => 2,
                'isbn' => '9789976000011',
                'title' => 'Advanced Biology Form Five',
                'author' => 'Dr. L. Mwakalukwa',
                'publisher' => 'Mkuki na Nyota',
                'edition' => '1st',
                'year_published' => 2021,
                'category' => 'Science',
                'price' => 18000,
                'quantity' => 10,
                'available_quantity' => 10,
                'rack_number' => 'S2-R1',
                'status' => 'available',
            ],
            [
                'school_id' => 2,
                'isbn' => '9789976000012',
                'title' => 'Physics Practical Guide',
                'author' => 'L. Mboya',
                'publisher' => 'Macmillan',
                'edition' => '2nd',
                'year_published' => 2022,
                'category' => 'Science',
                'price' => 16000,
                'quantity' => 8,
                'available_quantity' => 6,
                'rack_number' => 'S2-R2',
                'status' => 'available',
            ],
            [
                'school_id' => 2,
                'isbn' => '9789976000013',
                'title' => 'Advanced Mathematics - A Level',
                'author' => 'M. Fundikira',
                'publisher' => 'TIE',
                'edition' => '1st',
                'year_published' => 2020,
                'category' => 'Mathematics',
                'price' => 19000,
                'quantity' => 9,
                'available_quantity' => 9,
                'rack_number' => 'M2-R1',
                'status' => 'available',
            ],
            [
                'school_id' => 2,
                'isbn' => '9789976000014',
                'title' => 'English Comprehension Skills',
                'author' => 'J. Mshana',
                'publisher' => 'Longhorn Publishers',
                'edition' => '3rd',
                'year_published' => 2019,
                'category' => 'Languages',
                'price' => 12500,
                'quantity' => 10,
                'available_quantity' => 10,
                'rack_number' => 'L2-R1',
                'status' => 'available',
            ],
            [
                'school_id' => 2,
                'isbn' => '9789976000015',
                'title' => 'Kiswahili Fasiha',
                'author' => 'Z. Mwakyusa',
                'publisher' => 'Oxford EA',
                'edition' => '2nd',
                'year_published' => 2017,
                'category' => 'Languages',
                'price' => 10000,
                'quantity' => 12,
                'available_quantity' => 11,
                'rack_number' => 'L2-R2',
                'status' => 'available',
            ],
            [
                'school_id' => 2,
                'isbn' => '9789976000016',
                'title' => 'Map Reading and Interpretation',
                'author' => 'T. Kamugisha',
                'publisher' => 'TIE',
                'edition' => '1st',
                'year_published' => 2016,
                'category' => 'Geography',
                'price' => 13000,
                'quantity' => 10,
                'available_quantity' => 9,
                'rack_number' => 'G2-R1',
                'status' => 'available',
            ],
            [
                'school_id' => 2,
                'isbn' => '9789976000017',
                'title' => 'Civic and Moral Education',
                'author' => 'F. Mwakipesile',
                'publisher' => 'Macmillan',
                'edition' => '2nd',
                'year_published' => 2018,
                'category' => 'Civics',
                'price' => 11000,
                'quantity' => 14,
                'available_quantity' => 13,
                'rack_number' => 'C2-R1',
                'status' => 'available',
            ],
            [
                'school_id' => 2,
                'isbn' => '9789976000018',
                'title' => 'History of Tanzania',
                'author' => 'A. Rugemalira',
                'publisher' => 'Tanzania Education Publishers',
                'edition' => '1st',
                'year_published' => 2015,
                'category' => 'History',
                'price' => 14000,
                'quantity' => 10,
                'available_quantity' => 9,
                'rack_number' => 'H2-R1',
                'status' => 'available',
            ],
            [
                'school_id' => 2,
                'isbn' => '9789976000019',
                'title' => 'Principles of Commerce',
                'author' => 'R. Lusekelo',
                'publisher' => 'Eastern Africa Books',
                'edition' => '3rd',
                'year_published' => 2021,
                'category' => 'Business',
                'price' => 15000,
                'quantity' => 11,
                'available_quantity' => 11,
                'rack_number' => 'B2-R1',
                'status' => 'available',
            ],
        ];

        foreach ($books as $book) {
            LibraryBook::create($book);
        }
    }
}
